# Generated by Django 4.1.4 on 2022-12-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_lox'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'qual_types',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LOX',
        ),
    ]
