# Generated by Django 4.1.4 on 2023-01-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_qualificationtype_delete_lox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tims_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ausm_tier', models.IntegerField()),
            ],
            options={
                'db_table': 'person_line',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pilot',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='org',
        ),
        migrations.AlterModelTable(
            name='pilotorganization',
            table='pilot_org',
        ),
        migrations.AlterModelTable(
            name='pilotqualification',
            table='pilot_qual',
        ),
        migrations.AlterModelTable(
            name='qualification',
            table='qual',
        ),
        migrations.AlterModelTable(
            name='qualificationtype',
            table='qual_type',
        ),
    ]
