# Generated by Django 4.1.4 on 2022-12-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_pilot_qualification_pilotqualification_delete_lox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilotqualification',
            options={'managed': False},
        ),
    ]
