# Generated by Django 4.1.4 on 2023-01-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'duty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'duty_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShellDuty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'shell_duty',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='line',
            table='shell_line',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='org',
        ),
    ]
