# Generated by Django 4.1.4 on 2022-12-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prsn_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'pilots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'quals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PilotQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.pilot')),
                ('qual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.qualification')),
            ],
        ),
        migrations.DeleteModel(
            name='LOX',
        ),
    ]
