# Generated by Django 4.1.4 on 2022-12-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0005_remove_pilotqualification_pilot_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('start_date_time', models.DateTimeField()),
                ('fly_go', models.IntegerField()),
            ],
            options={
                'db_table': 'shell_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'orgs',
                'managed': False,
            },
        ),
    ]
